/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Colecao.View;

import Colecao.Model.usuario_marca;
import Colecao.Model.Usuario_mini;
import javax.swing.JOptionPane;
import Colecao.Data.Usuario_miniD;
import java.util.logging.Level;
import java.util.logging.Logger;
import Colecao.Model.Usuario_c;
public class JFCad_miniaturas extends javax.swing.JFrame {

    private usuario_marca obj_m;
    private Usuario_mini obj;
    private Usuario_miniD obj_mini;
    private Usuario_c obj_c;
    
    public JFCad_miniaturas(usuario_marca obj_m){
        this();
        this.obj_m = obj_m;
    }
    public JFCad_miniaturas() {
        initComponents();
        obj_m = new usuario_marca();
        obj = new Usuario_mini();
        obj_c = new Usuario_c();
        try {
            obj_mini = new Usuario_miniD();
        } catch (Exception ex) {
            Logger.getLogger(JFCad_miniaturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNOME_M = new javax.swing.JLabel();
        jBsalvar = new javax.swing.JButton();
        jBNova = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLESCALA_M = new javax.swing.JLabel();
        jLANOLANCAMENTO_M = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLnumero_id = new javax.swing.JLabel();
        jTnome_m = new javax.swing.JTextField();
        jTcor_m = new javax.swing.JTextField();
        jTanolancamento_m = new javax.swing.JTextField();
        jTescala_miniatura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNOME_M.setBackground(new java.awt.Color(0, 0, 204));
        jLNOME_M.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLNOME_M.setText("NOME");

        jBsalvar.setBackground(new java.awt.Color(102, 255, 0));
        jBsalvar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBsalvar.setForeground(new java.awt.Color(255, 255, 255));
        jBsalvar.setText("SALVAR");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBNova.setBackground(new java.awt.Color(51, 255, 0));
        jBNova.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBNova.setForeground(new java.awt.Color(255, 255, 255));
        jBNova.setText("NOVA");
        jBNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovaActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 255, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("VISUALIZAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLESCALA_M.setBackground(new java.awt.Color(0, 0, 204));
        jLESCALA_M.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLESCALA_M.setText("ESCALA");

        jLANOLANCAMENTO_M.setBackground(new java.awt.Color(0, 0, 204));
        jLANOLANCAMENTO_M.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLANOLANCAMENTO_M.setText("ANO DE LANCAMENTO");

        jLabel4.setBackground(new java.awt.Color(0, 0, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("COR");

        jLabel5.setBackground(new java.awt.Color(0, 0, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("ID");

        jLnumero_id.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLnumero_id.setText("0");

        jTnome_m.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jTcor_m.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jTanolancamento_m.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jTescala_miniatura.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jBNova)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBsalvar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLNOME_M, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196)
                        .addComponent(jTnome_m, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLANOLANCAMENTO_M)
                            .addComponent(jLESCALA_M, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTcor_m)
                                .addComponent(jTanolancamento_m)
                                .addComponent(jTescala_miniatura, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                            .addComponent(jLnumero_id, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLnumero_id)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLNOME_M, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jTnome_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLANOLANCAMENTO_M)
                    .addComponent(jTanolancamento_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLESCALA_M)
                    .addComponent(jTescala_miniatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTcor_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsalvar)
                    .addComponent(jBNova)
                    .addComponent(jButton3))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
     JOptionPane.showMessageDialog(null, ""+obj_m.getNome_marca());
     try{
           if(validarCampos()){
               if(preencherObjeto()){
                   if(obj_mini.incluir_M(obj)){
                       JOptionPane.showMessageDialog(this, "Miniatura salva com sucesso!",
                                "Meu sistema", JOptionPane.INFORMATION_MESSAGE);
                       limpar_campos();
                   }
               }
           }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(this, "Erro ao salvar"+ erro.getMessage(), "Sistema",JOptionPane.ERROR_MESSAGE);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovaActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Cadastrar miniatura de outra marca?")==JOptionPane.YES_OPTION)  {
            obj_c.setIdc(8);         
            new JFtela_Interatividade(obj_c).setVisible(true);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jBNovaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new JFTABELAADM().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCad_miniaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCad_miniaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCad_miniaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCad_miniaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCad_miniaturas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBNova;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLANOLANCAMENTO_M;
    private javax.swing.JLabel jLESCALA_M;
    private javax.swing.JLabel jLNOME_M;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLnumero_id;
    private javax.swing.JTextField jTanolancamento_m;
    private javax.swing.JTextField jTcor_m;
    private javax.swing.JTextField jTescala_miniatura;
    private javax.swing.JTextField jTnome_m;
    // End of variables declaration//GEN-END:variables
    
    private boolean validarCampos() {
        String msg = "";//varavel com funcao de soma, onde a cada if algo novo pode ser adicionado
        if (jTnome_m.getText().length() < 5 || jTnome_m.getText().length() > 100) {
            msg += "\nO campo nome deve conter pelo menos 5 caracteres";
        }
        if (jTanolancamento_m.getText().length() !=4 ) {
            msg += "\nO campo de ano de lancamento esta incorreto";
        } 
        
        if (jTescala_miniatura.getText().length() < 3 || jTescala_miniatura.getText().length() > 10) {
            msg += "\nO campo escala é invalido";
        }
        if (jTcor_m.getText().length() < 3 || jTcor_m.getText().length() > 30) {
            msg += "\nO campo cor precisa ser preenchido";
        }
        if (msg.isEmpty()) {
            return true;//funcao.isempty serve para contar se o numero de caracteres é = 0(lengty()==0), //
        } //ou seja, se esssa variavel msg esta vazia
        else {
            JOptionPane.showMessageDialog(this, "Os campos abaixo precisam de atenção:"
                    + msg, "Atenção", JOptionPane.ERROR_MESSAGE);
        }
        return false;//se esse metodo for falso, em sua chamada ele ira retornar a mensagem acima e
        // false, para dizer ao metodo que chamar para parar
    }
    private boolean preencherObjeto() throws Exception{
        obj.setNumero_id(Integer.parseInt(jLnumero_id.getText()));
        obj.setNome(jTnome_m.getText());
        obj.setAnolancamento(Integer.parseInt(jTanolancamento_m.getText()));
        obj.setCor(jTcor_m.getText());
        obj.setEscala(jTescala_miniatura.getText());
        obj.setMarca(obj_m.getLogo_marca());
        return true;
    }
    private void limpar_campos(){
       jTanolancamento_m.setText("");
       jTcor_m.setText("");
       jTescala_miniatura.setText("");
       jTnome_m.setText("");
    }
}
