/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Colecao.View;

import Colecao.Model.Usuario_c;
import Colecao.Data.Usuario_Data;
//import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class JFinicio extends javax.swing.JFrame {
    private Usuario_c obj;
    private Usuario_Data objUsu_data;
     /* Creates new form JFinicio
     */
    public JFinicio() {
        
        initComponents();
        obj = new Usuario_c();
        try {
            objUsu_data = new Usuario_Data();
        } catch (Exception ex) {
            Logger.getLogger(JFinicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jLID_acesso.setVisible(false);
        jLsenha_i.setVisible(false);
        jTID_acesso.setVisible(false);
        jTsenha_i.setVisible(false);
        jBir.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTITULO = new javax.swing.JLabel();
        jBacessar = new javax.swing.JButton();
        jTID_acesso = new javax.swing.JTextField();
        jTsenha_i = new javax.swing.JTextField();
        jLID_acesso = new javax.swing.JLabel();
        jLsenha_i = new javax.swing.JLabel();
        TITULO_A = new javax.swing.JLabel();
        jBbem_vindo = new javax.swing.JButton();
        jBir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Sua Coleçao"); // NOI18N

        jLTITULO.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLTITULO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTITULO.setText("É UM COLECIONADOR");

        jBacessar.setBackground(new java.awt.Color(0, 0, 204));
        jBacessar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBacessar.setForeground(new java.awt.Color(255, 255, 255));
        jBacessar.setText("ACESSAR");
        jBacessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBacessarActionPerformed(evt);
            }
        });

        jLID_acesso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLID_acesso.setText("ID");

        jLsenha_i.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLsenha_i.setText("SENHA");
        jLsenha_i.setOpaque(true);

        TITULO_A.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TITULO_A.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TITULO_A.setText("AINDA NAO?");

        jBbem_vindo.setBackground(new java.awt.Color(0, 0, 255));
        jBbem_vindo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBbem_vindo.setForeground(new java.awt.Color(255, 255, 255));
        jBbem_vindo.setText("BEM VINDO");
        jBbem_vindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbem_vindoActionPerformed(evt);
            }
        });

        jBir.setBackground(new java.awt.Color(0, 204, 0));
        jBir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBir.setForeground(new java.awt.Color(255, 255, 255));
        jBir.setText("IR");
        jBir.setOpaque(false);
        jBir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLID_acesso))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jTID_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLsenha_i)
                    .addComponent(jTsenha_i, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jBacessar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(TITULO_A, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jBbem_vindo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jBir)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLTITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jBacessar)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLsenha_i, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLID_acesso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTID_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTsenha_i, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jBir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TITULO_A, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jBbem_vindo)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBacessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBacessarActionPerformed
        jLID_acesso.setVisible(true);
        jLsenha_i.setVisible(true);
        jTID_acesso.setVisible(true);
        jTsenha_i.setVisible(true);
        jBir.setVisible(true);
    }//GEN-LAST:event_jBacessarActionPerformed

    private void jBbem_vindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbem_vindoActionPerformed
        new JFCad_Usuarios().setVisible(true); 
        dispose();
    }//GEN-LAST:event_jBbem_vindoActionPerformed

    private void jBirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBirActionPerformed
        try {
            if(preencherobjeto_ir()){
                if(objUsu_data.validar(obj)) {
                    JOptionPane.showMessageDialog(null, "Seja muito bem vindo "+ obj.getNome());
                    new JFtela_Interatividade(obj).setVisible(true);//chamei o construtor da outra tela passando o oobj pra ela
                }
                else JOptionPane.showMessageDialog(null, "id ou senha inválidos");
            } 
        } catch (Exception ex) {
            Logger.getLogger(JFinicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFinicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFinicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITULO_A;
    private javax.swing.JButton jBacessar;
    private javax.swing.JButton jBbem_vindo;
    private javax.swing.JButton jBir;
    private javax.swing.JLabel jLID_acesso;
    private javax.swing.JLabel jLTITULO;
    private javax.swing.JLabel jLsenha_i;
    private javax.swing.JTextField jTID_acesso;
    private javax.swing.JTextField jTsenha_i;
    // End of variables declaration//GEN-END:variables

private boolean preencherobjeto_ir() throws Exception{    
        obj.setSenha(jTsenha_i.getText());
        obj.setIdc(Integer.parseInt(jTID_acesso.getText()));
        return true;
}    
/* private boolean preencherObjeto() throws Exception{
        obj.setId(Integer.parseInt(jLnumeroID.getText()));
        obj.setNome(jTnome_usuario.getText());
        obj.setEmail(jTemail_usuario.getText());
        obj.setSenha(jPSenha_usuario.getText());
        obj.setTipo(jCTipo_usuario.getSelectedIndex());
        return true;
    }*/
}
