/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Colecao.View;



import Colecao.Model.Usuario_c;
import Colecao.Model.Usuario_mini;
import java.util.ArrayList;
import Colecao.Data.Possui_mini;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
        
        
public class JFTabela_colecao extends javax.swing.JFrame {
    
    private ArrayList<Usuario_mini> listademiniaturas;
    private Usuario_c obj;
    private Usuario_mini obj_mini;
    private Possui_mini psmini;
    
    public JFTabela_colecao(Usuario_c obj){
    this();//pra que serve essa linha
    this.obj= obj;
    }
    public JFTabela_colecao() {
        initComponents();
        try {
            psmini = new Possui_mini();
        } catch (Exception ex) {
            Logger.getLogger(JFTabela_colecao.class.getName()).log(Level.SEVERE, null, ex);
        }
        obj = new Usuario_c();
        obj_mini = new Usuario_mini();
        listademiniaturas = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTTABELA_COLECIONADOR = new javax.swing.JTable();
        jTPESQUISAR_COLECIONADOR = new javax.swing.JTextField();
        jBPESQUISAR_COLECIONADOR = new javax.swing.JButton();
        jBPESQUISAR_NO_BANCO = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTABELA_BANCO = new javax.swing.JTable();
        jTPESQUISAR_NOBANCO = new javax.swing.JTextField();
        jBADICIONAR = new javax.swing.JButton();
        jBremover = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTTABELA_COLECIONADOR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTTABELA_COLECIONADOR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cor", "Marca", "Escala", "Lançamento", "ID da miniatura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTTABELA_COLECIONADOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTABELA_COLECIONADORMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTTABELA_COLECIONADOR);

        jTPESQUISAR_COLECIONADOR.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTPESQUISAR_COLECIONADOR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTPESQUISAR_COLECIONADORKeyReleased(evt);
            }
        });

        jBPESQUISAR_COLECIONADOR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBPESQUISAR_COLECIONADOR.setText("SUAS MINIATURAS");
        jBPESQUISAR_COLECIONADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPESQUISAR_COLECIONADORActionPerformed(evt);
            }
        });

        jBPESQUISAR_NO_BANCO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBPESQUISAR_NO_BANCO.setText("NOVAS MINIATURAS");

        jTTABELA_BANCO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTTABELA_BANCO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cor", "Marca", "Escala", "Lançamento", "ID da miniatura"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTTABELA_BANCO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTTABELA_BANCOMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTTABELA_BANCO);

        jTPESQUISAR_NOBANCO.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTPESQUISAR_NOBANCO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTPESQUISAR_NOBANCOKeyReleased(evt);
            }
        });

        jBADICIONAR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBADICIONAR.setText("ADICIONAR");
        jBADICIONAR.setEnabled(false);
        jBADICIONAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBADICIONARActionPerformed(evt);
            }
        });

        jBremover.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBremover.setText("REMOVER");
        jBremover.setEnabled(false);
        jBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBremoverActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("SAIR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBPESQUISAR_NO_BANCO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTPESQUISAR_NOBANCO))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBADICIONAR)
                        .addGap(176, 176, 176)
                        .addComponent(jBremover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBPESQUISAR_COLECIONADOR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTPESQUISAR_COLECIONADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPESQUISAR_NO_BANCO)
                    .addComponent(jTPESQUISAR_NOBANCO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBADICIONAR)
                    .addComponent(jBremover)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPESQUISAR_COLECIONADOR)
                    .addComponent(jTPESQUISAR_COLECIONADOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPESQUISAR_NOBANCOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPESQUISAR_NOBANCOKeyReleased
        try{
            inativar();
            jTTABELA_BANCO.setEnabled(true);
            listademiniaturas = psmini.pesquisar_mini_banco(jTPESQUISAR_NOBANCO.getText(), obj);//passar por parametro
            DefaultTableModel mp = (DefaultTableModel)jTTABELA_BANCO.getModel();
            mp.setNumRows(0);//serve para toda vez que a tabela pesquisar alguma coisa, a cada nova pesquisa por um aletra, 
                                                                                //a pesquisa anterior acaba zerando(se apaga)
            for(Usuario_mini u: listademiniaturas)
             mp.addRow(new String[]{u.getNome(),u.getCor(),u.getMarca(),u.getEscala(),""+u.getAnolancamento(),""+u.getNumero_id()});
        }catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao pesquisar:"+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTPESQUISAR_NOBANCOKeyReleased

    private void jTTABELA_BANCOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTABELA_BANCOMouseClicked
        int linhaSelecionada = jTTABELA_BANCO.getSelectedRow();
        if(linhaSelecionada>-1){
            
            
            obj_mini.setNumero_id(listademiniaturas.get(linhaSelecionada).getNumero_id());
            obj_mini.setNome(listademiniaturas.get(linhaSelecionada).getNome());
            inativar();
            jBADICIONAR.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTTABELA_BANCOMouseClicked

    private void jBADICIONARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBADICIONARActionPerformed
        try {
            psmini.Adicionar(obj, obj_mini); 
            JOptionPane.showMessageDialog(null, "Parabens "+obj.getNome()+" pela aquisiçao de sua nova miniatura. "+obj_mini.getNome());// TODO add your handling code here:
            DefaultTableModel mp = (DefaultTableModel)jTTABELA_BANCO.getModel();
            mp.setNumRows(0);
        } catch (Exception ex) {
            Logger.getLogger(JFTabela_colecao.class.getName()).log(Level.SEVERE, null, ex);
        }
        inativar();
    }//GEN-LAST:event_jBADICIONARActionPerformed

    private void jBPESQUISAR_COLECIONADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPESQUISAR_COLECIONADORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPESQUISAR_COLECIONADORActionPerformed

    private void jBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBremoverActionPerformed
        if(JOptionPane.showConfirmDialog(this, obj.getNome()+" deseja remover a miniatura "+ obj_mini.getNome()+ " de sua coleção")== JOptionPane.YES_OPTION){
            try {
                psmini.excluir(obj, obj_mini);
                DefaultTableModel mp = (DefaultTableModel)jTTABELA_COLECIONADOR.getModel();
                mp.setNumRows(0);
                } catch (Exception ex) {
                Logger.getLogger(JFTabela_colecao.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBremoverActionPerformed

    private void jTPESQUISAR_COLECIONADORKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTPESQUISAR_COLECIONADORKeyReleased
        try{
            inativar();
            jTTABELA_COLECIONADOR.setEnabled(true);
            listademiniaturas = psmini.pesquisar_mini_colecionador(jTPESQUISAR_COLECIONADOR.getText(), obj);//passar por parametro
            DefaultTableModel mp = (DefaultTableModel)jTTABELA_COLECIONADOR.getModel();
            mp.setNumRows(0);//serve para toda vez que a tabela pesquisar alguma coisa, a cada nova pesquisa por um aletra, 
                                                                                //a pesquisa anterior acaba zerando(se apaga)
            for(Usuario_mini u: listademiniaturas)
             mp.addRow(new String[]{u.getNome(),u.getCor(),u.getMarca(),u.getEscala(),""+u.getAnolancamento(),""+u.getNumero_id()});
        }catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao pesquisar:"+e.getMessage());
        }        // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jTPESQUISAR_COLECIONADORKeyReleased

    private void jTTABELA_COLECIONADORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTTABELA_COLECIONADORMouseClicked
       
        int linhaSelecionada = jTTABELA_COLECIONADOR.getSelectedRow();
        
        if(linhaSelecionada>-1){
            
            obj_mini.setNumero_id(listademiniaturas.get(linhaSelecionada).getNumero_id());
            obj_mini.setNome(listademiniaturas.get(linhaSelecionada).getNome()); 
            inativar();
            jBremover.setEnabled(true);
        }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jTTABELA_COLECIONADORMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new JFtela_Interatividade(obj).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTabela_colecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTabela_colecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTabela_colecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTabela_colecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTabela_colecao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBADICIONAR;
    private javax.swing.JButton jBPESQUISAR_COLECIONADOR;
    private javax.swing.JButton jBPESQUISAR_NO_BANCO;
    private javax.swing.JButton jBremover;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTPESQUISAR_COLECIONADOR;
    private javax.swing.JTextField jTPESQUISAR_NOBANCO;
    private javax.swing.JTable jTTABELA_BANCO;
    private javax.swing.JTable jTTABELA_COLECIONADOR;
    // End of variables declaration//GEN-END:variables

    
    public void inativar(){
        jTTABELA_COLECIONADOR.setEnabled(false);
        jTTABELA_BANCO.setEnabled(false);
        jBremover.setEnabled(false);
        jBADICIONAR.setEnabled(false);
    }
}
