/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Colecao.View;


import Colecao.Data.Usuario_miniD;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Colecao.Model.Usuario_mini;
import Colecao.Model.Usuario_c;

public class JFTABELAADM extends javax.swing.JFrame {
    
    private Usuario_c obj;
    private Usuario_miniD DAO;
    private ArrayList<Usuario_mini> listademiniaturas;
    
    public JFTABELAADM() {
        initComponents();
        
        obj = new Usuario_c();
        try {
            DAO = new Usuario_miniD();
        } catch (Exception ex) {
            Logger.getLogger(JFTABELAADM.class.getName()).log(Level.SEVERE, null, ex);
        }
        listademiniaturas= new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela_demini = new javax.swing.JTable();
        jBsair = new javax.swing.JButton();
        jBAdicionar = new javax.swing.JButton();
        jTtexto_pesquisa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabela_demini.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTabela_demini.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cor", "Marca", "Escala", "Ano de lancamento", "Número de ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabela_demini);

        jBsair.setBackground(new java.awt.Color(255, 51, 102));
        jBsair.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBsair.setText("SAIR");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jBAdicionar.setBackground(new java.awt.Color(51, 204, 0));
        jBAdicionar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBAdicionar.setText("ADICIONAR NOVA");
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });

        jTtexto_pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTtexto_pesquisaKeyReleased(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("PESQUISA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jBsair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBAdicionar)
                .addGap(260, 260, 260))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton3)
                        .addGap(73, 73, 73)
                        .addComponent(jTtexto_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTtexto_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBsair)
                    .addComponent(jBAdicionar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTtexto_pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtexto_pesquisaKeyReleased
        try{
            listademiniaturas = DAO.pesquisar(jTtexto_pesquisa.getText());
            DefaultTableModel mp = (DefaultTableModel)jTabela_demini.getModel();
            mp.setNumRows(0);//serve para toda vez que a tabela pesquisar alguma coisa, a cada nova pesquisa por um aletra, 
                                                                                //a pesquisa anterior acaba zerando(se apaga)
            for(Usuario_mini u: listademiniaturas)
             mp.addRow(new String[]{u.getNome(),u.getCor(),u.getMarca(),u.getEscala(),""+u.getAnolancamento(),""+u.getNumero_id()});
        }catch(Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao pesquisar:"+e.getMessage());
        }
//        try {
//            listademiniaturas = DAO.pesquisar(jTtexto_pesquisa.getText());
//            DefaultTableModel mp = (DefaultTableModel)jtbtabela_de_dados.getModel();
//            mp.setNumRows(0);//serve para toda vez que a tabela pesquisar alguma coisa, a cada nova pesquisa por um aletra, 
//                                                                                //a pesquisa anterior acaba zerando(se apaga)
//            for(Usuario u: listaDeUsuarios)
//             mp.addRow(new String[]{""+u.getId(),u.getNome(),u.getEmail()});
//        } catch (Exception e) {
//        JOptionPane.showMessageDialog(this, "Erro ao pesquisar:"+e.getMessage());
//        }          // TODO add your handling code here:
    }//GEN-LAST:event_jTtexto_pesquisaKeyReleased

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        if(JOptionPane.showConfirmDialog(this,"Deseja mesmo sair")==JOptionPane.YES_OPTION){
            obj.setIdc(8);
            new JFtela_Interatividade(obj).setVisible(true);
            dispose();
        }   /*if(JOptionPane.showConfirmDialog(this, "Administrar banco de miniaturas?")==JOptionPane.YES_OPTION)*/// TODO add your handling code here:
    }//GEN-LAST:event_jBsairActionPerformed

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        obj.setIdc(8);
            new JFtela_Interatividade(obj).setVisible(true);
            dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFTABELAADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFTABELAADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFTABELAADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFTABELAADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFTABELAADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela_demini;
    private javax.swing.JTextField jTtexto_pesquisa;
    // End of variables declaration//GEN-END:variables
}
