/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Colecao.View;
import Colecao.View.JFCad_Usuarios;
import javax.swing.JOptionPane;
import Colecao.Model.Usuario_c;//dados do colecionador
import Colecao.Model.usuario_marca;
import Colecao.Data.Usuario_marcaD;
import java.util.logging.Level;
import java.util.logging.Logger;
public class JFtela_Interatividade extends javax.swing.JFrame {
    private JFCad_Usuarios objCD;
    private Usuario_c obj;
    private usuario_marca obj_m;
    private Usuario_marcaD obj_marca;
    /**
     * Creates new form JFtela_Interatividade
    */
//    //public JFtela_Interatividade(){
//        visivel_ativo();
//    }
    public JFtela_Interatividade(Usuario_c obj){//aqui eu crio um construtor vindo ja com um obj da classe usuario c(o cara da model)
        this();
        this.obj=obj;
    }
    public JFtela_Interatividade() {
        initComponents();
        obj_m = new usuario_marca();
        obj = new Usuario_c();
        objCD = new JFCad_Usuarios();
        try {
            obj_marca= new Usuario_marcaD();
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }
        jBAUTOWORD_I.setVisible(false);
        jBGRENLIGHT_I.setVisible(false);
        jBHW_I.setVisible(false);
        jBpmg_I.setVisible(false);
        jBJONNYLIGHT_I.setVisible(false);
        jBKYOSHO_I.setVisible(false);
        jBM2_I.setVisible(false);
        jBMAISTO_I.setVisible(false);
        jBMCE_I.setVisible(false);
        jBMINIGT_I.setVisible(false);
        
        jBTARMAC_I.setVisible(false);
        jBTIMEMICRO_I.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBvisualizar_TI = new javax.swing.JButton();
        jBeditar_TI = new javax.swing.JButton();
        jBcadastrar_TI = new javax.swing.JButton();
        jBHW_I = new javax.swing.JButton();
        jBMAISTO_I = new javax.swing.JButton();
        jBGRENLIGHT_I = new javax.swing.JButton();
        jBM2_I = new javax.swing.JButton();
        jBTIMEMICRO_I = new javax.swing.JButton();
        jBMINIGT_I = new javax.swing.JButton();
        jBTARMAC_I = new javax.swing.JButton();
        jBKYOSHO_I = new javax.swing.JButton();
        jBAUTOWORD_I = new javax.swing.JButton();
        jBMCE_I = new javax.swing.JButton();
        jBJONNYLIGHT_I = new javax.swing.JButton();
        jBpmg_I = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBvisualizar_TI.setBackground(new java.awt.Color(0, 0, 204));
        jBvisualizar_TI.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBvisualizar_TI.setForeground(new java.awt.Color(255, 255, 255));
        jBvisualizar_TI.setText("VISUALIZAR COLEÇÃO");
        jBvisualizar_TI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvisualizar_TIActionPerformed(evt);
            }
        });

        jBeditar_TI.setBackground(new java.awt.Color(0, 51, 204));
        jBeditar_TI.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBeditar_TI.setForeground(new java.awt.Color(255, 255, 255));
        jBeditar_TI.setText("EDITAR");
        jBeditar_TI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeditar_TIActionPerformed(evt);
            }
        });

        jBcadastrar_TI.setBackground(new java.awt.Color(0, 51, 204));
        jBcadastrar_TI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBcadastrar_TI.setForeground(new java.awt.Color(255, 255, 255));
        jBcadastrar_TI.setText("CADASTRAR NOVA");
        jBcadastrar_TI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadastrar_TIActionPerformed(evt);
            }
        });

        jBHW_I.setText("HW");
        jBHW_I.setEnabled(false);
        jBHW_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHW_IActionPerformed(evt);
            }
        });

        jBMAISTO_I.setText("MAISTO");
        jBMAISTO_I.setEnabled(false);
        jBMAISTO_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMAISTO_IActionPerformed(evt);
            }
        });

        jBGRENLIGHT_I.setText("GL");
        jBGRENLIGHT_I.setEnabled(false);
        jBGRENLIGHT_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGRENLIGHT_IActionPerformed(evt);
            }
        });

        jBM2_I.setText("M2");
        jBM2_I.setEnabled(false);
        jBM2_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBM2_IActionPerformed(evt);
            }
        });

        jBTIMEMICRO_I.setText("TIMEMICRO");
        jBTIMEMICRO_I.setEnabled(false);
        jBTIMEMICRO_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTIMEMICRO_IActionPerformed(evt);
            }
        });

        jBMINIGT_I.setText("MINIGT");
        jBMINIGT_I.setEnabled(false);
        jBMINIGT_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMINIGT_IActionPerformed(evt);
            }
        });

        jBTARMAC_I.setText("TARMAC");
        jBTARMAC_I.setEnabled(false);
        jBTARMAC_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTARMAC_IActionPerformed(evt);
            }
        });

        jBKYOSHO_I.setText("KYOSHO");
        jBKYOSHO_I.setEnabled(false);
        jBKYOSHO_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBKYOSHO_IActionPerformed(evt);
            }
        });

        jBAUTOWORD_I.setText("AUTOWORD");
        jBAUTOWORD_I.setEnabled(false);
        jBAUTOWORD_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAUTOWORD_IActionPerformed(evt);
            }
        });

        jBMCE_I.setText("MCE");
        jBMCE_I.setEnabled(false);
        jBMCE_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMCE_IActionPerformed(evt);
            }
        });

        jBJONNYLIGHT_I.setText("JONNY");
        jBJONNYLIGHT_I.setEnabled(false);
        jBJONNYLIGHT_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBJONNYLIGHT_IActionPerformed(evt);
            }
        });

        jBpmg_I.setText("PMG");
        jBpmg_I.setEnabled(false);
        jBpmg_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpmg_IActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBcadastrar_TI)
                    .addComponent(jBeditar_TI)
                    .addComponent(jBvisualizar_TI, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBHW_I)
                    .addComponent(jBGRENLIGHT_I)
                    .addComponent(jBTIMEMICRO_I)
                    .addComponent(jBTARMAC_I)
                    .addComponent(jBAUTOWORD_I)
                    .addComponent(jBJONNYLIGHT_I))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBpmg_I)
                    .addComponent(jBMCE_I)
                    .addComponent(jBKYOSHO_I)
                    .addComponent(jBMINIGT_I)
                    .addComponent(jBM2_I)
                    .addComponent(jBMAISTO_I, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBvisualizar_TI, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBHW_I)
                        .addComponent(jBMAISTO_I)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBM2_I)
                    .addComponent(jBGRENLIGHT_I))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jBeditar_TI))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBTIMEMICRO_I)
                            .addComponent(jBMINIGT_I))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jBcadastrar_TI))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBTARMAC_I)
                            .addComponent(jBKYOSHO_I))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBAUTOWORD_I)
                            .addComponent(jBMCE_I))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBJONNYLIGHT_I)
                    .addComponent(jBpmg_I))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBeditar_TIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeditar_TIActionPerformed
        //chamar o metodo editando la da classe jfcad_usuarios
        new JFCad_Usuarios(obj).setVisible(true);//adicionei o obj na chamada
        
       
       // vchamar um metodo que validar os botoes da tela de cadstro e preencha as tela la.
            // TODO add your handling code here:
    }//GEN-LAST:event_jBeditar_TIActionPerformed

    private void jBcadastrar_TIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadastrar_TIActionPerformed
        try {
            if(obj.getIdc()==8){
                if(JOptionPane.showConfirmDialog(this, "Administrar banco de miniaturas?")==JOptionPane.YES_OPTION){
                    visivel_ativo();
                }
                else {new JFTabela_colecao(obj).setVisible(true);   
                  dispose();}
            }
            else {new JFTabela_colecao(obj).setVisible(true);   
                  dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir: "+e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jBcadastrar_TIActionPerformed

    private void jBHW_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHW_IActionPerformed
        try {
            obj_m.setLogo_marca("HW");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBHW_IActionPerformed

    private void jBMAISTO_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMAISTO_IActionPerformed
        try {
            obj_m.setLogo_marca("MT");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jBMAISTO_IActionPerformed

    private void jBGRENLIGHT_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGRENLIGHT_IActionPerformed
        try {
            obj_m.setLogo_marca("GL");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBGRENLIGHT_IActionPerformed

    private void jBM2_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBM2_IActionPerformed
        try {
            obj_m.setLogo_marca("M2");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBM2_IActionPerformed

    private void jBTIMEMICRO_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTIMEMICRO_IActionPerformed
        try {
            obj_m.setLogo_marca("TM MIC");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBTIMEMICRO_IActionPerformed

    private void jBMINIGT_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMINIGT_IActionPerformed
        try {
            obj_m.setLogo_marca("MINI GT");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBMINIGT_IActionPerformed

    private void jBTARMAC_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTARMAC_IActionPerformed
        try {
            obj_m.setLogo_marca("TW");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBTARMAC_IActionPerformed

    private void jBKYOSHO_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBKYOSHO_IActionPerformed
        try {
            obj_m.setLogo_marca("KYOSHO");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBKYOSHO_IActionPerformed

    private void jBAUTOWORD_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAUTOWORD_IActionPerformed
        try {
            obj_m.setLogo_marca("AWD");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBAUTOWORD_IActionPerformed

    private void jBMCE_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMCE_IActionPerformed
        try {
            obj_m.setLogo_marca("MCE");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBMCE_IActionPerformed

    private void jBJONNYLIGHT_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBJONNYLIGHT_IActionPerformed
        try {
            obj_m.setLogo_marca("JL");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBJONNYLIGHT_IActionPerformed

    private void jBpmg_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpmg_IActionPerformed
        try {
            obj_m.setLogo_marca("PMG");
            obj_marca.pesquisa_marca(obj_m);
            new JFCad_miniaturas(obj_m).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(JFtela_Interatividade.class.getName()).log(Level.SEVERE, null, ex);
        }    // TODO add your handling code here:    // TODO add your handling code here:
    }//GEN-LAST:event_jBpmg_IActionPerformed

    private void jBvisualizar_TIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvisualizar_TIActionPerformed
        new JFTabela_colecao(obj).setVisible(true);   
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jBvisualizar_TIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFtela_Interatividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFtela_Interatividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFtela_Interatividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFtela_Interatividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater (new Runnable() {
            public void run() {
                new JFtela_Interatividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAUTOWORD_I;
    private javax.swing.JButton jBGRENLIGHT_I;
    private javax.swing.JButton jBHW_I;
    private javax.swing.JButton jBJONNYLIGHT_I;
    private javax.swing.JButton jBKYOSHO_I;
    private javax.swing.JButton jBM2_I;
    private javax.swing.JButton jBMAISTO_I;
    private javax.swing.JButton jBMCE_I;
    private javax.swing.JButton jBMINIGT_I;
    private javax.swing.JButton jBTARMAC_I;
    private javax.swing.JButton jBTIMEMICRO_I;
    private javax.swing.JButton jBcadastrar_TI;
    private javax.swing.JButton jBeditar_TI;
    private javax.swing.JButton jBpmg_I;
    private javax.swing.JButton jBvisualizar_TI;
    // End of variables declaration//GEN-END:variables

    private void visivel_ativo(){
       jBAUTOWORD_I.setVisible(true);
       jBGRENLIGHT_I.setVisible(true);
       jBHW_I.setVisible(true);
       jBpmg_I.setVisible(true);
       jBJONNYLIGHT_I.setVisible(true);
       jBKYOSHO_I.setVisible(true);
       jBM2_I.setVisible(true);
       jBMAISTO_I.setVisible(true);
       jBMCE_I.setVisible(true);
       jBMINIGT_I.setVisible(true);
       jBTARMAC_I.setVisible(true);
       jBTIMEMICRO_I.setVisible(true);
       jBAUTOWORD_I.setEnabled(true);
       jBGRENLIGHT_I.setEnabled(true);
       jBHW_I.setEnabled(true);
       jBpmg_I.setEnabled(true);
       jBJONNYLIGHT_I.setEnabled(true);
       jBKYOSHO_I.setEnabled(true);
       jBM2_I.setEnabled(true);
       jBMAISTO_I.setEnabled(true);
       jBMCE_I.setEnabled(true);
       jBMINIGT_I.setEnabled(true);
       jBTARMAC_I.setEnabled(true);
       jBTIMEMICRO_I.setEnabled(true);
    }
}
